[package]
name = "quosi"
version = "0.1.0"
lang = "C++17"

warn-level = "high"
iso-compliant = true

[profile.release]
opt-linktime = false

[dependencies]
quosi = { path="../lib" }
vmem  = { path="../../vmem" }

